### ISSUE TITLE
Replace bcrypt with bcryptjs

### ISSUE THREAD

**Issue by jimjamdev** [ghaiklor/sails-service-hash#21]

**Comment by ghaiklor** [comment]
@jimmyjamieson Why do we need replace with bcryptjs?

**Comment by jimjamdev** [comment]
bcrypt has all sorts of problems on windows with node-gyp. bcryptjs is a pure js implementation. It's easily replaced and much better :+1:

**Comment by ghaiklor** [comment]
@jimmyjamieson agreed. Will publish a minor update if `bcryptjs` is not break my tests.

**Comment by ghaiklor** [comment]
@jimmyjamieson published - https://github.com/ghaiklor/sails-service-hash/releases/tag/v3.1.0

**Comment by jimjamdev** [comment]
Excellent :) Maybe check if any of your other modules use it and replace :+1:

**Comment by ghaiklor** [comment]
@jimmyjamieson no, just here :smiley_cat:
